"""Serialization mechanics. Nothing outside the package hand-rolls YAML

1. write_atomic -- state.yaml. This is rewritten often and never left truncated
2. append_event -- events.jsonl. Written by many array tasks at once
3. render_stub -- metadata.yaml. This is written once and intended to be hand edited/commented
"""
from __future__ import annotations

import json
import os
import textwrap
from datetime import date, datetime
from enum import Enum
from pathlib import Path
from typing import Any, get_args

import yaml
from pydantic import BaseModel
from pydantic_core import PydanticUndefined

INDENT = "  "
COMMENT_WIDTH = 88
_MISSING = object()

# --- writes ---
def write_atomic(path: Path, text: str) -> None:
    """
    Write with a temp file and a rename. Stops killed/failed jobs from leaving a truncated YAML
    """
    tmp = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path) # atomic in a single filesystem

def append_event(path: Path, event: dict[str, Any]) -> None:
    """
    Append one JSON line at a time. Makes it safe for Slurm arrays
    Events are kept to one small line
    """
    line = json.dumps(event, separators=(",", ":"), sort_keys=True, default=str) + "\n"
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try:
        os.write(fd, line.encode("utf-8"))
    finally:
        os.close(fd)

def dump_state(model: BaseModel) -> str:
    """
    state.yaml uses a dump since it is intended for machine not human readability
    """
    header = (
        "# Generated by amms. Do NOT hand-edit: file is rewritten on every\n"
        "# `amms submit` / `amms scan`. Notes belong in metadata.yaml\n"
    )
    body = yaml.safe_dump(model.model_dump(mode="json"), sort_keys=False, default_flow_style=False)
    return header + body

# --- commented stub ---
def render_stub(model_cls: type[BaseModel], values: dict | None = None, *, level: int = 0) -> str:
    """
    Renders a commented YAML stub from pydantic model
    
    Comments are from Field(description=...) keeping the schema as the sole truth
    Protects from having to update the template when a new field is added
    """
    values = values or {}
    pad = INDENT * level
    out: list[str] = []

    for name, field in model_cls.model_fields.items():
        if field.description:
            out += [f"{pad}# {c}" for c in textwrap.wrap(field.description, COMMENT_WIDTH - len(pad))]

        given = values.get(name, _MISSING)
        nested = _nested_model(field.annotation)

        if nested is not None:
            out.append(f"{pad}{name}:")
            out.append(render_stub(nested, given if isinstance(given, dict) else {}, level=level+1))
        else:
            value = _default_of(field) if given is _MISSING else given
            if isinstance(value, dict) and value:
                out.append(f"{pad}{name}:")
                out += [f"{pad}{INDENT}{_scalar(k)}: {_scalar(v)}" for k, v in value.items()]
            elif isinstance(value, (list, tuple)) and value:
                out.append(f"{pad}{name}:")
                out += [f"{pad}{INDENT}- {_scalar(v)}" for v in value]
            else:
                out.append(f"{pad}{name}: {_scalar(value)}")

        if level == 0:
            out.append("")

    return "\n".join(out).rstrip() + "\n"

def _nested_model(annotation: Any) -> type[BaseModel] | None:
    """ Unwrap `Setup` and `Setup | None` alike"""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    for arg in get_args(annotation):
        if isinstance(arg, type) and issubclass(arg, BaseModel):
            return arg

    return None

def _default_of(field: Any) -> Any:
    if field.default is not PydanticUndefined:
        return field.default
    if field.default_factory is not None:
        return field.default_factory()
    return None

def _scalar(value: Any) -> str:
    """Return one YAML scalar, with PyYAML deciding when to use quotes"""
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, (date, datetime)):
        value = value.isoformat()
    if isinstance(value, BaseModel):
        value = value.model_dump(mode="json")
    dumped = yaml.safe_dump({"_": value}, sort_keys=False, default_flow_style=True)
    return dumped.split(":", 1)[1].strip()


